services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: zenlink # Database name
      POSTGRES_USER: user # Database user
      POSTGRES_PASSWORD: password # Database password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d zenlink"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  app:
    build: .
    environment:
      URL: "short.nnisarg.in"
      PORT: 5000
      MINUTES_TO_EXPIRE: 1440
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: zenlink
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "5000"
    deploy:
      replicas: 1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount Nginx configuration file
    ports:
      - "8080:80" # Exposing Nginx port on host (8080)
    networks:
      - app_network
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
